# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
src = 'src'
out = 'out'
evm_version = "cancun"
libs = ['lib']

# copy/pasta from https://docs.openzeppelin.com/upgrades-plugins/1.x/foundry-upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
 
viaIR = true 
# optimizer_runs = 1_000_000
